<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="XWJPMDD415" name="app.psc.testcases.accountverification.accountverificationtestcases" tests="5" failures="3" timestamp="13 Jul 2018 07:29:10 GMT" time="190.802" errors="0">
  <testcase name="TC008_02_Verify_Login_Flow_Security_Answer_Select_Security_Questions_Same" time="49.322" classname="app.psc.testcases.accountverification.accountverificationtestcases"/>
  <testcase name="TC008_00_Verify_new_user_flow_positive" time="69.614" classname="app.psc.testcases.accountverification.accountverificationtestcases"/>
  <testcase name="TC008_03_Verify_New_User_loginFlow_register_username_invalid_input" time="39.657" classname="app.psc.testcases.accountverification.accountverificationtestcases"/>
  <testcase name="TC008_00_Verify_new_user_flow_negative" time="18.649" classname="app.psc.testcases.accountverification.accountverificationtestcases">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at app.psc.testcases.accountverification.accountverificationtestcases.TC008_00_Verify_new_user_flow_negative(accountverificationtestcases.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC008_00_Verify_new_user_flow_negative -->
  <testcase name="TC008_03_Verify_New_User_loginFlow_register_username_invalid_input" time="13.560" classname="app.psc.testcases.accountverification.accountverificationtestcases"/>
</testsuite> <!-- app.psc.testcases.accountverification.accountverificationtestcases -->
