<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="XWJPMDD177" name="app.psc.testcases.login.logintestcases" tests="23" failures="7" timestamp="14 Dec 2017 10:25:46 GMT" time="652.915" errors="0">
  <testcase name="TC005_01_Verify_User_Account_Locking_For_Max_Invalid_Attempt" time="11.297" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC002_01_Verify_Existing_User_Error_Messages_PreLogin" time="13.532" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC017_01_Internal_Employee_External_Client_Login" time="11.139" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC002_01_Verify_Existing_User_Error_Messages_PreLogin" time="13.574" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC001_09_Verify_Jump_Page_Not_Displayed_When_AcessToPlanInSingleSite" time="105.110" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC007_01_display_correct_date_and_time_of_my_last_login" time="40.635" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC006_01_Verify_Force_Login" time="17.156" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC001_01_SIT_PSC_Sitenavigation_Menutabs" time="28.774" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC006_01_Verify_Error_Message_For_Terminated_User" time="17.090" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC002_01_Verify_Existing_User_Error_Messages_PreLogin" time="13.510" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC001_02_SIT_PSC_Sitenavigation_SubMenutabs" time="7.648" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC017_01_Internal_Employee_External_Client_Login" time="11.650" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC002_01_Verify_Existing_User_Error_Messages_PreLogin" time="15.363" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC01_SIT_PSC_HomePage_Transaction_Security" time="111.941" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC001_02_SIT_PSC_Sitenavigation_SubMenutabs" time="22.566" classname="app.psc.testcases.login.logintestcases">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at app.psc.testcases.login.logintestcases.TC001_02_SIT_PSC_Sitenavigation_SubMenutabs(logintestcases.java:560)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC001_02_SIT_PSC_Sitenavigation_SubMenutabs -->
  <testcase name="TC006_01_Verify_Error_Message_For_Terminated_User" time="21.313" classname="app.psc.testcases.login.logintestcases">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at app.psc.testcases.login.logintestcases.TC006_01_Verify_Error_Message_For_Terminated_User(logintestcases.java:504)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC006_01_Verify_Error_Message_For_Terminated_User -->
  <testcase name="TC05_01_SIT_PSC_HomePage_01_TC001_frame_on_Dashboard_Filesharing_and_Reports_pages" time="33.181" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC002_Verify_Jump_Page_Displayed_When_AcessToPlansInAllSites" time="44.872" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC003_UI_Validations_On_JumpPage" time="5.928" classname="app.psc.testcases.login.logintestcases">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at app.psc.testcases.login.logintestcases.TC003_UI_Validations_On_JumpPage(logintestcases.java:864)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC003_UI_Validations_On_JumpPage -->
  <testcase name="TC004_01_Verify_Header_and_Footer_Links_PreLogin" time="38.166" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC004_02_Verify_Header_and_Footer_Links_PostLogin" time="32.067" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC011_01_SIT_PSC_Login_01_TC020_Unsuccessful_login_attempts" time="21.499" classname="app.psc.testcases.login.logintestcases"/>
  <testcase name="TC004_Verify_PLUser_Login_With_No_Plna_Access" time="14.904" classname="app.psc.testcases.login.logintestcases"/>
</testsuite> <!-- app.psc.testcases.login.logintestcases -->
