<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="XWJPMDD177" name="app.psc.testcases.accountverification.accountverification_existingusr" tests="17" failures="12" timestamp="14 Dec 2017 10:25:47 GMT" time="789.073" errors="0">
  <testcase name="TC018_Security_Question_Validation_Existing_User" time="22.528" classname="app.psc.testcases.accountverification.accountverification_existingusr"/>
  <testcase name="TC019_Verify_Default_Plan_Prompting" time="23.366" classname="app.psc.testcases.accountverification.accountverification_existingusr"/>
  <testcase name="TC006_01_Verify_Display_Of_Notification_On_HomePage" time="117.710" classname="app.psc.testcases.accountverification.accountverification_existingusr"/>
  <testcase name="TC004_01_Verify_Changepasword_When_Password_Expired_Negative_Scenario" time="15.170" classname="app.psc.testcases.accountverification.accountverification_existingusr"/>
  <testcase name="TC004_02_Verify_Changepasword_When_Password_Expired_Positive_Flow" time="67.980" classname="app.psc.testcases.accountverification.accountverification_existingusr"/>
  <testcase name="TC005_01_Verify_PSC_Users_Are_Unbale_To_Reuse_Last_Ten_Passwords" time="21.640" classname="app.psc.testcases.accountverification.accountverification_existingusr">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at app.psc.testcases.accountverification.accountverification_existingusr.TC005_01_Verify_PSC_Users_Are_Unbale_To_Reuse_Last_Ten_Passwords(accountverification_existingusr.java:473)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC005_01_Verify_PSC_Users_Are_Unbale_To_Reuse_Last_Ten_Passwords -->
  <testcase name="TC013_SIT_PSC_HomePage_01_TC010_Regression_Testing_New_Pages" time="22.906" classname="app.psc.testcases.accountverification.accountverification_existingusr"/>
  <testcase name="TC004_01_Verify_Changepasword_When_Password_Expired_Negative_Scenario" time="13.747" classname="app.psc.testcases.accountverification.accountverification_existingusr">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at app.psc.testcases.accountverification.accountverification_existingusr.TC004_01_Verify_Changepasword_When_Password_Expired_Negative_Scenario(accountverification_existingusr.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC004_01_Verify_Changepasword_When_Password_Expired_Negative_Scenario -->
  <testcase name="TC006_01_Verify_Display_Of_Notification_On_HomePage" time="117.968" classname="app.psc.testcases.accountverification.accountverification_existingusr"/>
  <testcase name="TC013_SIT_PSC_HomePage_01_TC010_Regression_Testing_New_Pages" time="33.303" classname="app.psc.testcases.accountverification.accountverification_existingusr"/>
  <testcase name="TC004_01_Verify_Changepasword_When_Password_Expired_Negative_Scenario" time="15.296" classname="app.psc.testcases.accountverification.accountverification_existingusr"/>
  <testcase name="TC006_01_Verify_Display_Of_Compliance_On_HomePage" time="118.327" classname="app.psc.testcases.accountverification.accountverification_existingusr"/>
  <testcase name="TC012_SIT_PSC_HomePage_02_TC003_Compliance_Security" time="33.643" classname="app.psc.testcases.accountverification.accountverification_existingusr"/>
  <testcase name="TC009_01_Verify_Multifactoring" time="0.181" classname="app.psc.testcases.accountverification.accountverification_existingusr">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at app.psc.testcases.accountverification.accountverification_existingusr.TC009_01_Verify_Multifactoring(accountverification_existingusr.java:684)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC009_01_Verify_Multifactoring -->
  <testcase name="TC004_01_Verify_Changepasword_When_Password_Expired_Negative_Scenario" time="13.284" classname="app.psc.testcases.accountverification.accountverification_existingusr">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at app.psc.testcases.accountverification.accountverification_existingusr.TC004_01_Verify_Changepasword_When_Password_Expired_Negative_Scenario(accountverification_existingusr.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC004_01_Verify_Changepasword_When_Password_Expired_Negative_Scenario -->
  <testcase name="TC006_01_Verify_Display_Of_Compliance_On_HomePage" time="117.784" classname="app.psc.testcases.accountverification.accountverification_existingusr"/>
  <testcase name="TC012_SIT_PSC_HomePage_02_TC003_Compliance_Security" time="34.240" classname="app.psc.testcases.accountverification.accountverification_existingusr"/>
</testsuite> <!-- app.psc.testcases.accountverification.accountverification_existingusr -->
