<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="9" total="9" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="testsuite" duration-ms="1843" started-at="2017-11-17T09:57:02Z" finished-at="2017-11-17T09:57:04Z">
    <groups>
    </groups>
    <test name="Regression_Orange_Period_Execution_1" duration-ms="1843" started-at="2017-11-17T09:57:02Z" finished-at="2017-11-17T09:57:04Z">
      <class name="app.psc.testcases.myprofile.MyProfileTestCases">
        <test-method status="FAIL" signature="InitTest()[pri:0, instance:app.psc.testcases.myprofile.MyProfileTestCases@7085bdee]" name="InitTest" is-config="true" duration-ms="0" started-at="2017-11-17T15:27:02Z" finished-at="2017-11-17T15:27:02Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[nodeName cannot be null or empty]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: nodeName cannot be null or empty
	at com.aventstack.extentreports.ExtentTest.createNode(ExtentTest.java:159)
	at com.aventstack.extentreports.ExtentTest.createNode(ExtentTest.java:268)
	at lib.Reporter.initializeModule(Reporter.java:134)
	at app.psc.testcases.myprofile.MyProfileTestCases.InitTest(MyProfileTestCases.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitTest -->
        <test-method status="FAIL" signature="TC001_01_SIT_PSC_Update_My_profile_Default_Plan(int, java.util.Map)[pri:0, instance:app.psc.testcases.myprofile.MyProfileTestCases@7085bdee]" name="TC001_01_SIT_PSC_Update_My_profile_Default_Plan" duration-ms="624" started-at="2017-11-17T15:27:03Z" data-provider="setData" finished-at="2017-11-17T15:27:04Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at core.framework.TestListener.isFinalTestStatus(TestListener.java:78)
	at core.framework.TestListener.afterInvocation(TestListener.java:332)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:619)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:777)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_01_SIT_PSC_Update_My_profile_Default_Plan -->
        <test-method status="FAIL" signature="TC001_02_SIT_PSC_Update_My_profile_Default_Plan(int, java.util.Map)[pri:0, instance:app.psc.testcases.myprofile.MyProfileTestCases@7085bdee]" name="TC001_02_SIT_PSC_Update_My_profile_Default_Plan" duration-ms="32" started-at="2017-11-17T15:27:04Z" data-provider="setData" finished-at="2017-11-17T15:27:04Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at core.framework.TestListener.isFinalTestStatus(TestListener.java:78)
	at core.framework.TestListener.afterInvocation(TestListener.java:332)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:619)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:777)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_02_SIT_PSC_Update_My_profile_Default_Plan -->
        <test-method status="FAIL" signature="TC002_01_SIT_PSC_Update_Email_Address_Positive_Flow(int, java.util.Map)[pri:0, instance:app.psc.testcases.myprofile.MyProfileTestCases@7085bdee]" name="TC002_01_SIT_PSC_Update_Email_Address_Positive_Flow" duration-ms="16" started-at="2017-11-17T15:27:04Z" data-provider="setData" finished-at="2017-11-17T15:27:04Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at core.framework.TestListener.isFinalTestStatus(TestListener.java:78)
	at core.framework.TestListener.afterInvocation(TestListener.java:332)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:619)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:777)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002_01_SIT_PSC_Update_Email_Address_Positive_Flow -->
        <test-method status="FAIL" signature="TC002_02_SIT_PSC_Update_Email_Address_Negative_Flow(int, java.util.Map)[pri:0, instance:app.psc.testcases.myprofile.MyProfileTestCases@7085bdee]" name="TC002_02_SIT_PSC_Update_Email_Address_Negative_Flow" duration-ms="31" started-at="2017-11-17T15:27:04Z" data-provider="setData" finished-at="2017-11-17T15:27:04Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at core.framework.TestListener.isFinalTestStatus(TestListener.java:78)
	at core.framework.TestListener.afterInvocation(TestListener.java:332)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:619)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:777)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002_02_SIT_PSC_Update_Email_Address_Negative_Flow -->
        <test-method status="FAIL" signature="TC002_03_SIT_PSC_Update_Email_Address_Invalid_Password(int, java.util.Map)[pri:0, instance:app.psc.testcases.myprofile.MyProfileTestCases@7085bdee]" name="TC002_03_SIT_PSC_Update_Email_Address_Invalid_Password" duration-ms="31" started-at="2017-11-17T15:27:04Z" data-provider="setData" finished-at="2017-11-17T15:27:04Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at core.framework.TestListener.isFinalTestStatus(TestListener.java:78)
	at core.framework.TestListener.afterInvocation(TestListener.java:332)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:619)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:777)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002_03_SIT_PSC_Update_Email_Address_Invalid_Password -->
        <test-method status="FAIL" signature="TC003_01_SIT_PSC_Update_User_Name(int, java.util.Map)[pri:0, instance:app.psc.testcases.myprofile.MyProfileTestCases@7085bdee]" name="TC003_01_SIT_PSC_Update_User_Name" duration-ms="31" started-at="2017-11-17T15:27:04Z" data-provider="setData" finished-at="2017-11-17T15:27:04Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at core.framework.TestListener.isFinalTestStatus(TestListener.java:78)
	at core.framework.TestListener.afterInvocation(TestListener.java:332)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:619)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:777)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC003_01_SIT_PSC_Update_User_Name -->
        <test-method status="FAIL" signature="TC004_01_SIT_PSC_Update_My_profile_Security_Questions(int, java.util.Map)[pri:0, instance:app.psc.testcases.myprofile.MyProfileTestCases@7085bdee]" name="TC004_01_SIT_PSC_Update_My_profile_Security_Questions" duration-ms="63" started-at="2017-11-17T15:27:04Z" data-provider="setData" finished-at="2017-11-17T15:27:04Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at core.framework.TestListener.isFinalTestStatus(TestListener.java:78)
	at core.framework.TestListener.afterInvocation(TestListener.java:332)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:619)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:777)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC004_01_SIT_PSC_Update_My_profile_Security_Questions -->
        <test-method status="FAIL" signature="TC005_01_SIT_PSC_Update_My_profile_Password(int, java.util.Map)[pri:0, instance:app.psc.testcases.myprofile.MyProfileTestCases@7085bdee]" name="TC005_01_SIT_PSC_Update_My_profile_Password" duration-ms="31" started-at="2017-11-17T15:27:04Z" data-provider="setData" finished-at="2017-11-17T15:27:04Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at core.framework.TestListener.isFinalTestStatus(TestListener.java:78)
	at core.framework.TestListener.afterInvocation(TestListener.java:332)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:619)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:777)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC005_01_SIT_PSC_Update_My_profile_Password -->
        <test-method status="FAIL" signature="TC006_01_FAQ_DDTC_245(int, java.util.Map)[pri:0, instance:app.psc.testcases.myprofile.MyProfileTestCases@7085bdee]" name="TC006_01_FAQ_DDTC_245" duration-ms="47" started-at="2017-11-17T15:27:04Z" data-provider="setData" finished-at="2017-11-17T15:27:04Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at core.framework.TestListener.isFinalTestStatus(TestListener.java:78)
	at core.framework.TestListener.afterInvocation(TestListener.java:332)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:619)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:777)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC006_01_FAQ_DDTC_245 -->
      </class> <!-- app.psc.testcases.myprofile.MyProfileTestCases -->
    </test> <!-- Regression_Orange_Period_Execution_1 -->
  </suite> <!-- testsuite -->
</testng-results>
